name: Golang with golangci-lint linting

inputs:
  version-golang:
    description: Golang version.
    default:
  version-golang-file:
    description: Golang version from go.mod. Used in place of `version-golang`.
    default:
  version-golangci-lint:
    description: golangci-lint version.
    required: true

runs:
  using: composite
  steps:
    - name: Setup Golang with cache
      uses: flipgroup/action-golang-with-cache@main
      with:
        version: ${{ inputs.version-golang }}
        version-file: ${{ inputs.version-golang-file }}
    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: ${{ inputs.version-golangci-lint }}
